### PR TITLE
Only Buy licenses you have meta data for

### PR DESCRIPTION
**Pull request by Flek26**
Update wording on My Info tab: https://i.imgur.com/6DVVHZF.png

With Meta Data for licenses: https://i.imgur.com/SKaMMsa.png
Without Meta Data: https://i.imgur.com/orP5uhO.png

Can now close using escape

### CODE REVIEW

**Comment by NietThijmen** [comment]
Hi @Flek26, i've just had 2 comments, would it be possible to maybe fix/answer them. Thanks in advance.

**Comment by Flek26** [comment]
> Hi @Flek26, i've just had 2 comments, would it be possible to maybe fix/answer them. Thanks in advance.

Sure what's up @legende11

**Comment by NietThijmen** [comment]
> > Hi @Flek26, i've just had 2 comments, would it be possible to maybe fix/answer them. Thanks in advance.
> 
> Sure what's up @legende11 

In client/nui.lua you at line 58 you hardcoded the items[1] would this have any reason? As that makes it less configurable

And the other one i appear to be stupid, as Player licenses doesnt have a number as key. So i thats fine

**Comment by Flek26** [comment]
> > > Hi @Flek26, i've just had 2 comments, would it be possible to maybe fix/answer them. Thanks in advance.
> > 
> > Sure what's up @legende11 
> 
> In client/nui.lua you at line 58 you hardcoded the items[1] would this have any reason? As that makes it less configurable
> 
> And the other one i appear to be stupid, as Player licenses doesnt have a number as key. So i thats fine 

The reason for that is ID_Card does not contain a Meta option for it. So this way ID_Card is always allowed to be purchased. If you don't want them able to purchase id_card - remove the hard code option and remove it from the config.

**Comment by NietThijmen** [comment]
LGTM

**Pull request merged**
